### PR TITLE
NSMenuItem checkmarks

### PR DESCRIPTION
**Pull request by markrickert**
Adds the ability to put this in your hash:

``` ruby
checked: true
```

to produce something like this:
screenshot 2014-07-16 14 35 49

setting it to false and updating the menu clears the checkmark.

:sparkles: Fully tested! :sparkles:

### CODE REVIEW

**Comment by mseeks** [comment]
<3

**Comment by markrickert** [comment]
Hope you guys don't mind me extending the `NSMenuItem` base class here. It just makes everything SO much easier!

**Comment by markrickert** [comment]
:heart: More PRs coming soon! One specifically will be to support your own UIView in the menu item.

**Comment by brianpattison** [comment]
@markrickert I did add `#checked?` back in as an alias method in 0.1.5 just now. Thanks!

**Comment by markrickert** [comment]
Sweet! Thanks for the merge!

**Pull request merged**
